name: Ensure book types are up to date

on: [push]

jobs:
  scrape_book_types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      
      - name: Install Python deps
        run: pip install -e .
      
      - name: Scrape book types
        run: |
          python scrape_book_types.py > book_types.py.new
          mv book_types.py.new src/HexBug/utils/book_types.py
          python -m black src/HexBug/utils/book_types.py

      - name: Ensure the scrape had no effect
        run: git diff --exit-code
