name: Ensure book types are up to date

on: [push]

jobs:
  scrape_book_types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      
      - name: Scrape book types
        run: python scrape_book_types.py | tee utils/book_types.py && python -m black utils/book_types.py

      - name: Ensure the scrape had no effect
        run: git diff --exit-code -s
